<?php
/**
 * PriceListProductJsonldPriceListProductWriteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Product API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VentureLeap\ProductService;

/**
 * PriceListProductJsonldPriceListProductWriteTest Class Doc Comment
 *
 * @category    Class
 * @description PriceListProductJsonldPriceListProductWrite
 * @package     VentureLeap\ProductService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceListProductJsonldPriceListProductWriteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriceListProductJsonldPriceListProductWrite"
     */
    public function testPriceListProductJsonldPriceListProductWrite()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "gross_price_per_unit"
     */
    public function testPropertyGrossPricePerUnit()
    {
    }

    /**
     * Test attribute "price_list"
     */
    public function testPropertyPriceList()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {
    }
}
