<?php
/**
 * PriceListProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Product API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\ProductService;

use VentureLeap\ProductService\Configuration;
use VentureLeap\ProductService\ApiException;
use VentureLeap\ProductService\ObjectSerializer;

/**
 * PriceListProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PriceListProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePriceListProductItem
     *
     * Removes the PriceListProduct resource..
     *
     */
    public function testDeletePriceListProductItem()
    {
    }

    /**
     * Test case for getPriceListProductCollection
     *
     * Retrieves the collection of PriceListProduct resources..
     *
     */
    public function testGetPriceListProductCollection()
    {
    }

    /**
     * Test case for getPriceListProductItem
     *
     * Retrieves a PriceListProduct resource..
     *
     */
    public function testGetPriceListProductItem()
    {
    }

    /**
     * Test case for patchPriceListProductItem
     *
     * Updates the PriceListProduct resource..
     *
     */
    public function testPatchPriceListProductItem()
    {
    }

    /**
     * Test case for postPriceListProductCollection
     *
     * Creates a PriceListProduct resource..
     *
     */
    public function testPostPriceListProductCollection()
    {
    }

    /**
     * Test case for putPriceListProductItem
     *
     * Replaces the PriceListProduct resource..
     *
     */
    public function testPutPriceListProductItem()
    {
    }
}
