<?php
/**
 * PriceListApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Product API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\ProductService;

use VentureLeap\ProductService\Configuration;
use VentureLeap\ProductService\ApiException;
use VentureLeap\ProductService\ObjectSerializer;

/**
 * PriceListApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PriceListApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePriceListItem
     *
     * Removes the PriceList resource..
     *
     */
    public function testDeletePriceListItem()
    {
    }

    /**
     * Test case for getPriceListCollection
     *
     * Retrieves the collection of PriceList resources..
     *
     */
    public function testGetPriceListCollection()
    {
    }

    /**
     * Test case for getPriceListItem
     *
     * Retrieves a PriceList resource..
     *
     */
    public function testGetPriceListItem()
    {
    }

    /**
     * Test case for patchPriceListItem
     *
     * Updates the PriceList resource..
     *
     */
    public function testPatchPriceListItem()
    {
    }

    /**
     * Test case for postPriceListCollection
     *
     * Creates a PriceList resource..
     *
     */
    public function testPostPriceListCollection()
    {
    }

    /**
     * Test case for putPriceListItem
     *
     * Replaces the PriceList resource..
     *
     */
    public function testPutPriceListItem()
    {
    }
}
