<?php
/**
 * ProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
* OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use {{invokerPackage}}\Configuration;
use {{invokerPackage}}\ApiException;
use {{invokerPackage}}\ObjectSerializer;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteProductItem
     *
     * Removes the Product resource..
     *
     */
    public function testDeleteProductItem()
    {
    }

    /**
     * Test case for getProductCollection
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testGetProductCollection()
    {
    }

    /**
     * Test case for getProductItem
     *
     * Retrieves a Product resource..
     *
     */
    public function testGetProductItem()
    {
    }

    /**
     * Test case for patchProductItem
     *
     * Updates the Product resource..
     *
     */
    public function testPatchProductItem()
    {
    }

    /**
     * Test case for postProductCollection
     *
     * Creates a Product resource..
     *
     */
    public function testPostProductCollection()
    {
    }

    /**
     * Test case for putProductItem
     *
     * Replaces the Product resource..
     *
     */
    public function testPutProductItem()
    {
    }
}
