<?php
/**
 * ProductCategoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Product API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\ProductService;

use VentureLeap\ProductService\Configuration;
use VentureLeap\ProductService\ApiException;
use VentureLeap\ProductService\ObjectSerializer;

/**
 * ProductCategoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\ProductService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductCategoryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteProductCategoryItem
     *
     * Removes the ProductCategory resource..
     *
     */
    public function testDeleteProductCategoryItem()
    {
    }

    /**
     * Test case for getProductCategoryCollection
     *
     * Retrieves the collection of ProductCategory resources..
     *
     */
    public function testGetProductCategoryCollection()
    {
    }

    /**
     * Test case for getProductCategoryItem
     *
     * Retrieves a ProductCategory resource..
     *
     */
    public function testGetProductCategoryItem()
    {
    }

    /**
     * Test case for postProductCategoryCollection
     *
     * Creates a ProductCategory resource..
     *
     */
    public function testPostProductCategoryCollection()
    {
    }

    /**
     * Test case for putProductCategoryItem
     *
     * Replaces the ProductCategory resource..
     *
     */
    public function testPutProductCategoryItem()
    {
    }
}
